// GEGENEREERD door scripts/generate-texts.mjs uit packages/teksten/*.json. Niet met de hand wijzigen.
// Draai `node scripts/generate-texts.mjs` na elke wijziging in packages/teksten.

enum GeneratedTexts {
    /// sha256 over taalkeuze.json en de 20 taalbestanden, in die volgorde.
    static let sourceHash = "412e5010976193ac3d4d2c16473665ee6a67dbe1cc43498f9861277cbc20fcef"

    /// De 20 taalcodes, in de volgorde van taalkeuze.json.
    static let languages: [String] = ["en", "nl", "de", "fr", "es", "pt", "it", "pl", "tr", "ru", "uk", "sv", "da", "nb", "ja", "ko", "zh-Hans", "zh-Hant", "ar", "hi"]

    /// De 22 sleutels, in de volgorde van en.json.
    static let keys: [String] = ["tabLabel", "title", "general", "specific", "commentGeneral", "commentSpecific", "pointHint", "pointStart", "pointBanner", "cancel", "send", "sending", "retry", "removeImage", "imageRemoved", "privacyNote", "sent", "close", "errorSend", "errorComment", "elementNone", "unavailable"]

    static let lang_en: [String: String] = [
        "tabLabel": "Feedback",
        "title": "Send feedback",
        "general": "General",
        "specific": "Point at something",
        "commentGeneral": "What would you like to tell us?",
        "commentSpecific": "What is wrong or could be better here?",
        "pointHint": "Tap the part of the screen you mean. We take a picture of this screen when you do.",
        "pointStart": "Point at an element",
        "pointBanner": "Tap what you mean",
        "cancel": "Cancel",
        "send": "Send",
        "sending": "Sending...",
        "retry": "Try again",
        "removeImage": "Remove image",
        "imageRemoved": "Image removed. Only your comment is sent.",
        "privacyNote": "Your feedback goes to the maker of this app.",
        "sent": "Thanks, your feedback was sent.",
        "close": "Close",
        "errorSend": "Sending failed. Your feedback is still here.",
        "errorComment": "Write a short comment.",
        "elementNone": "No specific element found",
        "unavailable": "Feedback is not available right now.",
    ]

    static let lang_nl: [String: String] = [
        "tabLabel": "Feedback",
        "title": "Feedback sturen",
        "general": "Algemeen",
        "specific": "Wijs iets aan",
        "commentGeneral": "Wat wil je ons laten weten?",
        "commentSpecific": "Wat is hier mis of kan beter?",
        "pointHint": "Tik op het deel van het scherm dat je bedoelt. Dan maken we een afbeelding van dit scherm.",
        "pointStart": "Wijs een element aan",
        "pointBanner": "Tik op wat je bedoelt",
        "cancel": "Annuleren",
        "send": "Versturen",
        "sending": "Bezig met versturen...",
        "retry": "Opnieuw",
        "removeImage": "Afbeelding weghalen",
        "imageRemoved": "Afbeelding weggehaald. Alleen je opmerking gaat mee.",
        "privacyNote": "Je feedback gaat naar de maker van deze app.",
        "sent": "Bedankt, je feedback is verstuurd.",
        "close": "Sluiten",
        "errorSend": "Versturen is mislukt. Je feedback staat er nog.",
        "errorComment": "Schrijf een korte opmerking.",
        "elementNone": "Geen specifiek element gevonden",
        "unavailable": "Feedback is nu niet beschikbaar.",
    ]

    static let lang_de: [String: String] = [
        "tabLabel": "Feedback",
        "title": "Feedback senden",
        "general": "Allgemein",
        "specific": "Etwas zeigen",
        "commentGeneral": "Was möchtest du uns mitteilen?",
        "commentSpecific": "Was stimmt hier nicht oder könnte besser sein?",
        "pointHint": "Tippe auf die Stelle auf dem Bildschirm, die du meinst. Dabei machen wir einen Screenshot dieses Bildschirms.",
        "pointStart": "Element auswählen",
        "pointBanner": "Tippe auf die gemeinte Stelle",
        "cancel": "Abbrechen",
        "send": "Senden",
        "sending": "Wird gesendet…",
        "retry": "Erneut versuchen",
        "removeImage": "Bild entfernen",
        "imageRemoved": "Bild entfernt. Nur dein Kommentar wird gesendet.",
        "privacyNote": "Dein Feedback geht an den Entwickler dieser App.",
        "sent": "Danke, dein Feedback wurde gesendet.",
        "close": "Schließen",
        "errorSend": "Das Senden ist fehlgeschlagen. Dein Feedback ist noch da.",
        "errorComment": "Schreib einen kurzen Kommentar.",
        "elementNone": "Kein bestimmtes Element gefunden",
        "unavailable": "Feedback ist gerade nicht verfügbar.",
    ]

    static let lang_fr: [String: String] = [
        "tabLabel": "Votre avis",
        "title": "Envoyer un avis",
        "general": "Général",
        "specific": "Indiquer une zone",
        "commentGeneral": "Que souhaitez-vous nous dire ?",
        "commentSpecific": "Quel est le problème ici ou que pourrait-on améliorer ?",
        "pointHint": "Touchez la partie de l’écran que vous souhaitez désigner. Une capture de cet écran sera alors réalisée.",
        "pointStart": "Désigner un élément",
        "pointBanner": "Touchez la zone concernée",
        "cancel": "Annuler",
        "send": "Envoyer",
        "sending": "Envoi en cours…",
        "retry": "Réessayer",
        "removeImage": "Supprimer l’image",
        "imageRemoved": "Image supprimée. Seul votre commentaire sera envoyé.",
        "privacyNote": "Votre avis est transmis au créateur de cette application.",
        "sent": "Merci, votre avis a été envoyé.",
        "close": "Fermer",
        "errorSend": "L’envoi a échoué. Votre avis est toujours là.",
        "errorComment": "Rédigez un court commentaire.",
        "elementNone": "Aucun élément précis trouvé",
        "unavailable": "L’envoi d’avis est indisponible pour le moment.",
    ]

    static let lang_es: [String: String] = [
        "tabLabel": "Comentarios",
        "title": "Enviar comentarios",
        "general": "General",
        "specific": "Señalar algo",
        "commentGeneral": "¿Qué te gustaría contarnos?",
        "commentSpecific": "¿Qué falla aquí o qué se podría mejorar?",
        "pointHint": "Toca la parte de la pantalla a la que te refieres. Al hacerlo, tomaremos una captura de esta pantalla.",
        "pointStart": "Señalar un elemento",
        "pointBanner": "Toca lo que quieres señalar",
        "cancel": "Cancelar",
        "send": "Enviar",
        "sending": "Enviando…",
        "retry": "Reintentar",
        "removeImage": "Quitar imagen",
        "imageRemoved": "Imagen eliminada. Solo se enviará tu comentario.",
        "privacyNote": "Tus comentarios se envían al creador de esta app.",
        "sent": "Gracias, tus comentarios se han enviado.",
        "close": "Cerrar",
        "errorSend": "No se ha podido enviar. Tus comentarios siguen aquí.",
        "errorComment": "Escribe un comentario breve.",
        "elementNone": "No se ha encontrado ningún elemento específico",
        "unavailable": "No se pueden enviar comentarios en este momento.",
    ]

    static let lang_pt: [String: String] = [
        "tabLabel": "Feedback",
        "title": "Enviar feedback",
        "general": "Geral",
        "specific": "Apontar algo",
        "commentGeneral": "O que você gostaria de nos dizer?",
        "commentSpecific": "O que está errado ou poderia melhorar aqui?",
        "pointHint": "Toque na parte da tela que você quer indicar. Ao fazer isso, faremos uma captura desta tela.",
        "pointStart": "Apontar um elemento",
        "pointBanner": "Toque no que quer indicar",
        "cancel": "Cancelar",
        "send": "Enviar",
        "sending": "Enviando…",
        "retry": "Tentar novamente",
        "removeImage": "Remover imagem",
        "imageRemoved": "Imagem removida. Só seu comentário será enviado.",
        "privacyNote": "Seu feedback vai para quem criou este app.",
        "sent": "Obrigado! Seu feedback foi enviado.",
        "close": "Fechar",
        "errorSend": "Não foi possível enviar. Seu feedback continua aqui.",
        "errorComment": "Escreva um comentário breve.",
        "elementNone": "Nenhum elemento específico encontrado",
        "unavailable": "O feedback não está disponível no momento.",
    ]

    static let lang_it: [String: String] = [
        "tabLabel": "Feedback",
        "title": "Invia feedback",
        "general": "Generale",
        "specific": "Indica qualcosa",
        "commentGeneral": "Cosa vorresti dirci?",
        "commentSpecific": "Cosa non va o si potrebbe migliorare qui?",
        "pointHint": "Tocca la parte dello schermo che vuoi indicare. Quando lo fai, acquisiamo uno screenshot di questa schermata.",
        "pointStart": "Indica un elemento",
        "pointBanner": "Tocca ciò che vuoi indicare",
        "cancel": "Annulla",
        "send": "Invia",
        "sending": "Invio in corso…",
        "retry": "Riprova",
        "removeImage": "Rimuovi immagine",
        "imageRemoved": "Immagine rimossa. Verrà inviato solo il tuo commento.",
        "privacyNote": "Il tuo feedback viene inviato a chi ha creato questa app.",
        "sent": "Grazie, il tuo feedback è stato inviato.",
        "close": "Chiudi",
        "errorSend": "Invio non riuscito. Il tuo feedback è ancora qui.",
        "errorComment": "Scrivi un breve commento.",
        "elementNone": "Nessun elemento specifico trovato",
        "unavailable": "Al momento il feedback non è disponibile.",
    ]

    static let lang_pl: [String: String] = [
        "tabLabel": "Opinia",
        "title": "Wyślij opinię",
        "general": "Ogólna",
        "specific": "Wskaż coś",
        "commentGeneral": "Co chcesz nam przekazać?",
        "commentSpecific": "Co tu nie działa lub co można poprawić?",
        "pointHint": "Dotknij miejsca na ekranie, które masz na myśli. Zrobimy wtedy zrzut tego ekranu.",
        "pointStart": "Wskaż element",
        "pointBanner": "Dotknij miejsca, o które Ci chodzi",
        "cancel": "Anuluj",
        "send": "Wyślij",
        "sending": "Wysyłanie…",
        "retry": "Spróbuj ponownie",
        "removeImage": "Usuń zrzut ekranu",
        "imageRemoved": "Zrzut ekranu usunięty. Wyślemy tylko Twój komentarz.",
        "privacyNote": "Twoja opinia trafi do twórcy tej aplikacji.",
        "sent": "Dziękujemy, Twoja opinia została wysłana.",
        "close": "Zamknij",
        "errorSend": "Nie udało się wysłać. Twoja opinia nadal tu jest.",
        "errorComment": "Napisz krótki komentarz.",
        "elementNone": "Nie znaleziono konkretnego elementu",
        "unavailable": "Przesyłanie opinii jest teraz niedostępne.",
    ]

    static let lang_tr: [String: String] = [
        "tabLabel": "Görüş",
        "title": "Geri bildirim gönder",
        "general": "Genel",
        "specific": "Bir yer seçin",
        "commentGeneral": "Bize ne söylemek istersiniz?",
        "commentSpecific": "Burada ne sorun var veya ne daha iyi olabilir?",
        "pointHint": "Ekranda belirtmek istediğiniz yere dokunun. Dokunduğunuzda bu ekranın görüntüsünü alırız.",
        "pointStart": "Bir öğe seçin",
        "pointBanner": "Belirtmek istediğiniz yere dokunun",
        "cancel": "İptal",
        "send": "Gönder",
        "sending": "Gönderiliyor…",
        "retry": "Tekrar dene",
        "removeImage": "Görseli kaldır",
        "imageRemoved": "Görsel kaldırıldı. Yalnızca yorumunuz gönderilecek.",
        "privacyNote": "Geri bildiriminiz bu uygulamanın geliştiricisine iletilir.",
        "sent": "Teşekkürler, geri bildiriminiz gönderildi.",
        "close": "Kapat",
        "errorSend": "Gönderilemedi. Geri bildiriminiz hâlâ burada.",
        "errorComment": "Kısa bir yorum yazın.",
        "elementNone": "Belirli bir öğe bulunamadı",
        "unavailable": "Geri bildirim şu anda kullanılamıyor.",
    ]

    static let lang_ru: [String: String] = [
        "tabLabel": "Отзыв",
        "title": "Отправить отзыв",
        "general": "Общее",
        "specific": "Указать место",
        "commentGeneral": "Что вы хотите нам сообщить?",
        "commentSpecific": "Что здесь не так или что можно улучшить?",
        "pointHint": "Нажмите на ту часть экрана, которую хотите указать. При нажатии мы сделаем снимок этого экрана.",
        "pointStart": "Указать элемент",
        "pointBanner": "Нажмите на нужное место",
        "cancel": "Отмена",
        "send": "Отправить",
        "sending": "Отправка…",
        "retry": "Повторить",
        "removeImage": "Удалить изображение",
        "imageRemoved": "Изображение удалено. Будет отправлен только ваш комментарий.",
        "privacyNote": "Ваш отзыв получит разработчик этого приложения.",
        "sent": "Спасибо, ваш отзыв отправлен.",
        "close": "Закрыть",
        "errorSend": "Не удалось отправить. Текст отзыва не потерян.",
        "errorComment": "Напишите короткий комментарий.",
        "elementNone": "Конкретный элемент не найден",
        "unavailable": "Отправка отзывов сейчас недоступна.",
    ]

    static let lang_uk: [String: String] = [
        "tabLabel": "Відгук",
        "title": "Надіслати відгук",
        "general": "Загальне",
        "specific": "Вказати місце",
        "commentGeneral": "Що ви хочете нам повідомити?",
        "commentSpecific": "Що тут не так або що можна покращити?",
        "pointHint": "Торкніться тієї частини екрана, яку хочете вказати. Тоді ми зробимо знімок цього екрана.",
        "pointStart": "Вказати елемент",
        "pointBanner": "Торкніться потрібного місця",
        "cancel": "Скасувати",
        "send": "Надіслати",
        "sending": "Надсилання…",
        "retry": "Повторити",
        "removeImage": "Видалити зображення",
        "imageRemoved": "Зображення видалено. Буде надіслано лише ваш коментар.",
        "privacyNote": "Ваш відгук отримає розробник цього застосунку.",
        "sent": "Дякуємо, ваш відгук надіслано.",
        "close": "Закрити",
        "errorSend": "Не вдалося надіслати. Текст відгуку не втрачено.",
        "errorComment": "Напишіть короткий коментар.",
        "elementNone": "Конкретного елемента не знайдено",
        "unavailable": "Надсилання відгуків зараз недоступне.",
    ]

    static let lang_sv: [String: String] = [
        "tabLabel": "Feedback",
        "title": "Skicka feedback",
        "general": "Allmänt",
        "specific": "Peka ut något",
        "commentGeneral": "Vad vill du berätta för oss?",
        "commentSpecific": "Vad är fel eller kan bli bättre här?",
        "pointHint": "Tryck på den del av skärmen du menar. Då tar vi en skärmbild av den här skärmen.",
        "pointStart": "Peka ut ett element",
        "pointBanner": "Tryck där du menar",
        "cancel": "Avbryt",
        "send": "Skicka",
        "sending": "Skickar…",
        "retry": "Försök igen",
        "removeImage": "Ta bort bild",
        "imageRemoved": "Bilden har tagits bort. Bara din kommentar skickas.",
        "privacyNote": "Din feedback skickas till den som har skapat appen.",
        "sent": "Tack, din feedback har skickats.",
        "close": "Stäng",
        "errorSend": "Det gick inte att skicka. Din feedback finns kvar här.",
        "errorComment": "Skriv en kort kommentar.",
        "elementNone": "Inget specifikt element hittades",
        "unavailable": "Feedback är inte tillgänglig just nu.",
    ]

    static let lang_da: [String: String] = [
        "tabLabel": "Feedback",
        "title": "Send feedback",
        "general": "Generelt",
        "specific": "Udpeg noget",
        "commentGeneral": "Hvad vil du fortælle os?",
        "commentSpecific": "Hvad er galt eller kunne være bedre her?",
        "pointHint": "Tryk på den del af skærmen, du mener. Så tager vi et skærmbillede af denne skærm.",
        "pointStart": "Udpeg et element",
        "pointBanner": "Tryk på det, du mener",
        "cancel": "Annuller",
        "send": "Send",
        "sending": "Sender…",
        "retry": "Prøv igen",
        "removeImage": "Fjern billede",
        "imageRemoved": "Billedet er fjernet. Kun din kommentar bliver sendt.",
        "privacyNote": "Din feedback sendes til den, der har lavet denne app.",
        "sent": "Tak, din feedback er sendt.",
        "close": "Luk",
        "errorSend": "Kunne ikke sende. Din feedback er stadig her.",
        "errorComment": "Skriv en kort kommentar.",
        "elementNone": "Intet specifikt element fundet",
        "unavailable": "Feedback er ikke tilgængelig lige nu.",
    ]

    static let lang_nb: [String: String] = [
        "tabLabel": "Innspill",
        "title": "Send tilbakemelding",
        "general": "Generelt",
        "specific": "Pek på noe",
        "commentGeneral": "Hva vil du fortelle oss?",
        "commentSpecific": "Hva er galt eller kan bli bedre her?",
        "pointHint": "Trykk på den delen av skjermen du mener. Da tar vi et skjermbilde av denne skjermen.",
        "pointStart": "Pek på et element",
        "pointBanner": "Trykk på det du mener",
        "cancel": "Avbryt",
        "send": "Send",
        "sending": "Sender…",
        "retry": "Prøv igjen",
        "removeImage": "Fjern bilde",
        "imageRemoved": "Bildet er fjernet. Bare kommentaren din blir sendt.",
        "privacyNote": "Tilbakemeldingen din sendes til den som har laget denne appen.",
        "sent": "Takk, tilbakemeldingen din er sendt.",
        "close": "Lukk",
        "errorSend": "Kunne ikke sende. Tilbakemeldingen din er fortsatt her.",
        "errorComment": "Skriv en kort kommentar.",
        "elementNone": "Fant ikke noe bestemt element",
        "unavailable": "Tilbakemelding er ikke tilgjengelig akkurat nå.",
    ]

    static let lang_ja: [String: String] = [
        "tabLabel": "フィードバック",
        "title": "フィードバックを送信",
        "general": "全般",
        "specific": "場所を指定",
        "commentGeneral": "どのようなことを伝えたいですか？",
        "commentSpecific": "ここにどのような問題や改善点がありますか？",
        "pointHint": "画面上の伝えたい箇所をタップしてください。タップすると、この画面のスクリーンショットが撮影されます。",
        "pointStart": "要素を指定",
        "pointBanner": "伝えたい箇所をタップ",
        "cancel": "キャンセル",
        "send": "送信",
        "sending": "送信中…",
        "retry": "再試行",
        "removeImage": "画像を削除",
        "imageRemoved": "画像を削除しました。コメントのみ送信されます。",
        "privacyNote": "フィードバックはこのアプリの開発者に送信されます。",
        "sent": "ありがとうございます。フィードバックを送信しました。",
        "close": "閉じる",
        "errorSend": "送信できませんでした。入力したフィードバックはそのまま残っています。",
        "errorComment": "短いコメントを入力してください。",
        "elementNone": "該当する要素が見つかりませんでした",
        "unavailable": "現在、フィードバックは利用できません。",
    ]

    static let lang_ko: [String: String] = [
        "tabLabel": "피드백",
        "title": "피드백 보내기",
        "general": "일반",
        "specific": "위치 지정",
        "commentGeneral": "어떤 내용을 전하고 싶으신가요?",
        "commentSpecific": "여기에 어떤 문제가 있거나 무엇을 개선하면 좋을까요?",
        "pointHint": "화면에서 말씀하고 싶은 부분을 탭해 주세요. 탭하면 이 화면의 스크린샷이 촬영돼요.",
        "pointStart": "요소 지정",
        "pointBanner": "원하는 부분을 탭하세요",
        "cancel": "취소",
        "send": "보내기",
        "sending": "보내는 중…",
        "retry": "다시 시도",
        "removeImage": "이미지 삭제",
        "imageRemoved": "이미지가 삭제됐어요. 작성한 의견만 전송돼요.",
        "privacyNote": "피드백은 이 앱의 개발자에게 전달돼요.",
        "sent": "감사해요. 피드백을 보냈어요.",
        "close": "닫기",
        "errorSend": "보내지 못했어요. 작성한 피드백은 그대로 남아 있어요.",
        "errorComment": "짧은 의견을 작성해 주세요.",
        "elementNone": "해당하는 요소를 찾지 못했어요",
        "unavailable": "지금은 피드백을 이용할 수 없어요.",
    ]

    static let lang_zh_Hans: [String: String] = [
        "tabLabel": "反馈",
        "title": "发送反馈",
        "general": "一般反馈",
        "specific": "指定位置",
        "commentGeneral": "你想告诉我们什么？",
        "commentSpecific": "这里有什么问题，或可以如何改进？",
        "pointHint": "轻点屏幕上你想指出的位置。我们会在你轻点时截取当前屏幕。",
        "pointStart": "指定元素",
        "pointBanner": "轻点想指出的位置",
        "cancel": "取消",
        "send": "发送",
        "sending": "正在发送…",
        "retry": "重试",
        "removeImage": "移除图片",
        "imageRemoved": "图片已移除。只会发送你的留言。",
        "privacyNote": "你的反馈会发送给此应用的开发者。",
        "sent": "谢谢，反馈已发送。",
        "close": "关闭",
        "errorSend": "发送失败。你填写的反馈还在。",
        "errorComment": "请填写简短的留言。",
        "elementNone": "未找到具体元素",
        "unavailable": "反馈功能暂时不可用。",
    ]

    static let lang_zh_Hant: [String: String] = [
        "tabLabel": "意見回饋",
        "title": "傳送意見回饋",
        "general": "一般回饋",
        "specific": "指定位置",
        "commentGeneral": "你想告訴我們什麼？",
        "commentSpecific": "這裡有什麼問題，或可以如何改善？",
        "pointHint": "點一下螢幕上你想指出的位置。我們會在你點選時擷取目前的螢幕畫面。",
        "pointStart": "指定元件",
        "pointBanner": "點一下想指出的位置",
        "cancel": "取消",
        "send": "傳送",
        "sending": "傳送中⋯",
        "retry": "重試",
        "removeImage": "移除圖片",
        "imageRemoved": "已移除圖片。只會傳送你的留言。",
        "privacyNote": "你的意見會傳送給這個 App 的開發者。",
        "sent": "謝謝，已傳送你的意見。",
        "close": "關閉",
        "errorSend": "傳送失敗。你填寫的意見還在。",
        "errorComment": "請填寫簡短的留言。",
        "elementNone": "找不到對應的元件",
        "unavailable": "目前無法使用意見回饋功能。",
    ]

    static let lang_ar: [String: String] = [
        "tabLabel": "ملاحظات",
        "title": "إرسال ملاحظات",
        "general": "عام",
        "specific": "تحديد موضع",
        "commentGeneral": "ما الذي تود إخبارنا به؟",
        "commentSpecific": "ما المشكلة هنا أو ما الذي يمكن تحسينه؟",
        "pointHint": "اضغط على الجزء الذي تقصده من الشاشة. سنلتقط صورة لهذه الشاشة عند الضغط.",
        "pointStart": "تحديد عنصر",
        "pointBanner": "اضغط على الموضع المقصود",
        "cancel": "إلغاء",
        "send": "إرسال",
        "sending": "جارٍ الإرسال…",
        "retry": "إعادة المحاولة",
        "removeImage": "إزالة الصورة",
        "imageRemoved": "تمت إزالة الصورة. سيُرسل تعليقك فقط.",
        "privacyNote": "تصل ملاحظاتك إلى مطوّر هذا التطبيق.",
        "sent": "شكرًا، تم إرسال ملاحظاتك.",
        "close": "إغلاق",
        "errorSend": "تعذّر الإرسال. ملاحظاتك لا تزال هنا.",
        "errorComment": "اكتب تعليقًا قصيرًا.",
        "elementNone": "لم يتم العثور على عنصر محدد",
        "unavailable": "الملاحظات غير متاحة حاليًا.",
    ]

    static let lang_hi: [String: String] = [
        "tabLabel": "फ़ीडबैक",
        "title": "फ़ीडबैक भेजें",
        "general": "सामान्य",
        "specific": "जगह चुनें",
        "commentGeneral": "आप हमें क्या बताना चाहेंगे?",
        "commentSpecific": "यहाँ क्या समस्या है या क्या बेहतर हो सकता है?",
        "pointHint": "स्क्रीन के उस हिस्से पर टैप करें जिसके बारे में आप बताना चाहते हैं। टैप करते ही हम इस स्क्रीन का स्क्रीनशॉट लेंगे।",
        "pointStart": "स्क्रीन पर कोई हिस्सा चुनें",
        "pointBanner": "जिस जगह की बात है, वहाँ टैप करें",
        "cancel": "रद्द करें",
        "send": "भेजें",
        "sending": "भेजा जा रहा है…",
        "retry": "फिर से प्रयास करें",
        "removeImage": "इमेज हटाएँ",
        "imageRemoved": "इमेज हटा दी गई है। सिर्फ़ आपकी टिप्पणी भेजी जाएगी।",
        "privacyNote": "आपका फ़ीडबैक इस ऐप के डेवलपर को भेजा जाता है।",
        "sent": "धन्यवाद, आपका फ़ीडबैक भेज दिया गया है।",
        "close": "बंद करें",
        "errorSend": "भेजा नहीं जा सका। आपका फ़ीडबैक अभी भी यहाँ मौजूद है।",
        "errorComment": "एक छोटी टिप्पणी लिखें।",
        "elementNone": "कोई खास हिस्सा नहीं मिला",
        "unavailable": "फ़िलहाल फ़ीडबैक उपलब्ध नहीं है।",
    ]

    /// Taalcode naar de teksten van die taal.
    static let table: [String: [String: String]] = [
        "en": lang_en,
        "nl": lang_nl,
        "de": lang_de,
        "fr": lang_fr,
        "es": lang_es,
        "pt": lang_pt,
        "it": lang_it,
        "pl": lang_pl,
        "tr": lang_tr,
        "ru": lang_ru,
        "uk": lang_uk,
        "sv": lang_sv,
        "da": lang_da,
        "nb": lang_nb,
        "ja": lang_ja,
        "ko": lang_ko,
        "zh-Hans": lang_zh_Hans,
        "zh-Hant": lang_zh_Hant,
        "ar": lang_ar,
        "hi": lang_hi,
    ]
}
